- .github/workflows/post-merge.yml
> chore: change trigger on pipeline cd

- .github/workflows/post-merge.yml
> chore: remove condition on job execution

- .releaserc.json
This PR proposes to add the releaserc file to enable the release semantic action 
> chore: add releaserc file

- .github/workflows/post-merge.yml
> chore: remove openapi references from pipeline cd

- src/main/terraform/env/dev/terraform.tfvars
- src/main/terraform/env/prod/terraform.tfvars
- src/main/terraform/env/uat/terraform.tfvars
This PR proposes to rename the used-to-be tier-0 into the new mcshared naming.
> chore: [SRTP-110] rename domain tier0 to mcshared

- .github/workflows/post-merge.yml
> chore: fix image references

- .github/workflows/post-merge.yml
- src/main/terraform/container_app.tf
This PR proposes to fix the reference url in cd pipeline
> chore: fix pipeline cd image reference

- .github/workflows/post-merge.yml
- gradle.properties
> chore: Fix gradle version property format

- .github/workflows/post-merge.yml
- README.md
> fix: clean useless code

- src/main/terraform/container_app.tf
> chore: [SRTP-111] add probes to container app

- src/main/terraform/container_app.tf
> chore: add quotes to string in probe config

- .github/workflows/build-n-push-main.yml
- .github/workflows/deploy.yml
- .github/workflows/post-merge.yml
- src/main/terraform/container_app.tf
> chore: minor fixes on actions

- build.gradle
- src/main/resources/application.properties
- src/main/resources/custom.security
- src/main/terraform/container_app.tf
- src/main/terraform/data.tf
- src/main/terraform/env/cstar-d-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-p-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-u-weu-rtp/terraform.tfvars
- src/main/terraform/locals.tf
- src/main/terraform/variables.tf
Instrument microservice using OpenTelemetry with autoconfigured App Insights exporter
- instrument using official microsoft library compatible with native compilation
- disable jar signature verification for Azure see https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/developer-guide-overview#configuring-spring-boot-3
> feat: [SRTP-115] Instrumentation otel azure

- .github/workflows/post-merge.yml
> fix: github pat to bypass main push

- .github/workflows/ci.yml
- build.gradle
> chore: restore trigger in pipeline CI

- .github/workflows/post-merge.yml
> chore: add latest tag in retag step in deploy workflow

- src/main/java/it/gov/pagopa/rtp/activator/configuration/SecurityConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/controller/SendAPIControllerImpl.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/SendAPIControllerImplTest.java
This PR proposes to disable the authz check on `/rtps` endpoint
> fix: [SRTP-155] remove authz on endpoint rtps

- gradle.properties
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceImpl.java
Annotation of the Rtp and SepaRequestToPayRequestResourceDto classes with @RegisterForReflection to ensure correct inclusion in reflection during native compilation.
> fix: [SRTP-152] fix objectmapper problem

- gradle.properties
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceImpl.java
> fix: [SRTP-152] remove objectmapper

- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapper.java
> fix: Change big decimal visualization

- .github/workflows/post-merge.yml
This PR proposes to use the correct digest when deploy a new image.
When the image gets retagged and pushed, it changes the digest. Therefore the new value needs to be propagated correctly.
> chore: use the correct digest in deploy

- openapi/send.openapi.yaml
This PR proposes to add a status code returned when a Service Provider sends an RTP to a debtor that it didn't activated.
- change OpenAPI specification.
> feat: [SRTP-181] Add mismatch activation case

- src/main/terraform/env/cstar-d-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-p-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-u-weu-rtp/terraform.tfvars
- src/test/java/it/gov/pagopa/rtp/activator/configuration/ActivationPropertiesConfigTest.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImplTest.java
- src/test/resources/application.yaml
Fix the location bug by adding the URL to dev/uat/prod terraform files.
Adjust a test to take the URL from the application.yaml and not mock it.
> fix: [SRTP-185] Fix location bug, adjust a test

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandler.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImplTest.java
This PR proposes to fix the response status code in case the fiscal code passed by header do not match the pattern.
> fix: [SRTP-201] return 404 on find activation when user is not found

- openapi/send.openapi.yaml
- src/main/java/it/gov/pagopa/rtp/activator/controller/rtp/RtpDtoMapper.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/Rtp.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpEntity.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpMapper.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapper.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/rtp/RtpDtoMapperTest.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/rtp/SendAPIControllerImplTest.java
- src/test/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpDBRepositoryTest.java
- src/test/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpDtoMapperTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapperTest.java
Update protocolId name with PayTrxRef
Mapping fields from Rtp class to SRTP standard object to send
Update tests 
> feat: [SRTP-209] update mapping

- src/main/java/it/gov/pagopa/rtp/activator/controller/rtp/RtpExceptionHandler.java
This PR proposes to return a payload with the error description in case of non complaint request 
> fix: [SRTP-204] correct the bad request payload in send rtps

- build.gradle
This PR proposes to add the client generator from epc openapi.
> chore: [SRTP-147] add client generator for epc openapi

- build.gradle
- src/main/java/it/gov/pagopa/rtp/activator/RtpActivatorApplication.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/ApplicationConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/ServiceProviderConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceImpl.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapper.java
- src/main/resources/application.yaml
- src/main/terraform/env/cstar-d-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-p-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-u-weu-rtp/terraform.tfvars
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapperTest.java
- src/test/resources/application.yaml
This PR proposes to add the external http call to the epc mock. 
- refactor the srtpMapper with the new generated model from epc openapi (client version)
- add the external api call to service
> feat: [SRTP-132] forward send to epc mock

- openapi/activation.openapi.yaml
Align the swagger with that one present inside rtp-apis repo.
> fix: [SRTP-248] Align swagger with apis

- src/main/java/it/gov/pagopa/rtp/activator/configuration/ServiceProviderConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/controller/rtp/SendAPIControllerImpl.java
- src/main/resources/application.yaml
- src/main/terraform/env/cstar-d-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-p-weu-rtp/terraform.tfvars
- src/main/terraform/env/cstar-u-weu-rtp/terraform.tfvars
- src/test/java/it/gov/pagopa/rtp/activator/controller/rtp/SendAPIControllerImplTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceTest.java
- src/test/resources/application.yaml
This PR proposes to add the Location header to the send response according to openapi specification.
> fix: [SRTP-186] bugfix location header in send response

- build.gradle
- src/main/java/it/gov/pagopa/rtp/activator/RtpActivatorApplication.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/CacheConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/CachesConfigProperties.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/CaffeineCacheFactory.java
- src/main/resources/application.yaml
- src/test/java/it/gov/pagopa/rtp/activator/configuration/CacheConfigTest.java
- src/test/java/it/gov/pagopa/rtp/activator/configuration/CaffeineCacheFactoryTest.java
- src/test/resources/application.yaml
Addition of dynamically configured cache based on properties per single cache.
- New dependencies `spring-boot-starter-cache` and `caffeine`;
- dynamic config classes based on per-cache params.
This is preliminary work to be able to cache frequently used external resources.
> feat: [SRTP-288] add cache configs

- src/main/java/it/gov/pagopa/rtp/activator/domain/registryfile/OAuth2.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/registryfile/ServiceProvider.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/registryfile/TechnicalServiceProvider.java
- src/main/java/it/gov/pagopa/rtp/activator/integration/blobstorage/BlobStorageClientAzure.java
- src/main/java/it/gov/pagopa/rtp/activator/integration/blobstorage/ServiceProviderDataResponse.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/it/gov/pagopa/rtp/activator/integration/blobstorage/BlobStorageClientAzureTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceTest.java
Added parsing of registry file upon download from BLOB Storage.
Created model classes needed to deserialize registry file data:
- `TechnicalServiceProvider`;
- `ServiceProvider`;
- `OAuth2`.
Parsing needed to consume/transform registry file data.
> feat: [SRTP-287] create data classes for registry file deserialization

- build.gradle
This PR proposes to remove the null values from the EPC payload. 
> fix: [SRTP-308] remove null values from epc payload

- src/main/java/it/gov/pagopa/rtp/activator/RtpActivatorApplication.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/PagoPaConfigProperties.java
- src/main/java/it/gov/pagopa/rtp/activator/controller/rtp/RtpDtoMapper.java
- src/main/resources/application.yaml
- src/test/java/it/gov/pagopa/rtp/activator/controller/rtp/RtpDtoMapperTest.java
I replaced the IBAN field with a fictitious value
I added a value to the IBAN field in the `RtpDtoMapper` .
the problem that is solved is to populate the field with a fictitious IBAN that respects the formatting rules.
> feat: [SRTP-284] replace iban in RtpDtoMapper

- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceImpl.java
> fix: [SRTP-386] Add dto class to reflection binding inside sendrtpserviceimpl

- src/main/java/it/gov/pagopa/rtp/activator/configuration/ssl/DefaultSslContextFactory.java
Add insecure trust manager upon creating `SSL` context.
Add `InsecureTrustManagerFactory` to `SslContext`.
This is needed to trust all known `CA`s.
> fix: [SRTP-388] add insecure trust manager in SslContextFactory

- src/main/java/it/gov/pagopa/rtp/activator/utils/CertificateChecker.java
This PR enhances logging in the CertificateChecker by adding a warning log when a certificate mismatch occurs, improving visibility into potential validation issues.
Added a warning log for certificate mismatches and improved log messages for better context.
Clearer logging helps diagnose certificate validation issues more efficiently.
> fix: [SRTP-375] fix certificate mismatch message in CertificateChecker

- .github/workflows/component-test.yml
- .github/workflows/post-merge.yml
- src/test/postman/RTP-component-test.postman_collection.json
- src/test/postman/uat.postman_environment.json
This PR proposes to add post-deploy component test conducted through Postman.
- add Postman collection
- add test step at the end of the deployment
With this change we are more confident in environment promotions
> feat: [SRTP-143] add Postman post-deploy tests

- .github/workflows/post-merge.yml
> fix: [SRTP-143] Fix component test run

- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapper.java
> fix: [SRTP-403] Remove typo

- src/main/java/it/gov/pagopa/rtp/activator/controller/callback/RequestToPayUpdateApi.java
- src/main/java/it/gov/pagopa/rtp/activator/controller/callback/RequestToPayUpdateController.java
- src/main/java/it/gov/pagopa/rtp/activator/utils/CertificateChecker.java
- src/main/java/it/gov/pagopa/rtp/activator/utils/LoggingUtils.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/callback/RequestToPayUpdateControllerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/utils/CertificateCheckerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/utils/LoggingUtilsTest.java
This PR aims to deserialize/parse the `RTP` send callback request body and to log it.
The parsing  now retrieves the required `BIC` of the `Service Provider of Debtor` in order to match the certificate number provided in the request with the one stored in the registry file: said parsing is done on a `JsonNode` object, as current generated alternatives are not feasible to mimic the polymorphic structure of the request body.
The downside of this solution is that it lacks out-of-the-box validation, which needs to be performed manually.
- Used `Jackson`'s `JsonNode` type for request body in the callback controller;
- adapted `Service Provider of Debtor`'s `BIC` retrieval upon authorizing request in `CertificateChecker`.
This is preliminary work to pave the road for `RTP` status change inside …
> feat: [SRTP-347] add callback request deserialization and logging

- openapi/activation.openapi.yaml
- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImpl.java
- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandler.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/errors/PayerAlreadyExists.java
- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerService.java
- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImpl.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandlerTest.java
Here we want to pass the correct body and header when we respond with 409 error.
- Add a PayerAlreadyExist error handler.
- Customize the PayerAlreadyExist class.
- Update the Activation openapi yaml.
- Add relative tests
We have to be compliant with our openapi swagger.
> fix: [SRTP-414] Add body and header for the 409 error.

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandler.java
- src/main/resources/application.yaml
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandlerTest.java
There is a typo inside the 409 error header on the Location url field.
Location before fix:
`https://api-rtp.uat.cstar.pagopa.it/rtp/activation/activations//activations/<numebr>`
After fix:
`https://api-rtp.uat.cstar.pagopa.it/rtp/activation/activations/<numebr>
`
 
<br class="Apple-interchange-newline">
> fix: Fix a typo inside the 409 location.

- src/main/java/it/gov/pagopa/rtp/activator/configuration/ApplicationConfig.java
- src/main/java/it/gov/pagopa/rtp/activator/configuration/mtlswebclient/DefaultWebClientFactory.java
- src/test/java/it/gov/pagopa/rtp/activator/configuration/mtlswebclient/DefaultWebClientFactoryTest.java
This PR fixes the instantiation of `WebClient.Builder` class, avoiding making it a `Spring Bean`: this allows the creation of different instances avoiding the unwanted pollution of a single one.
- added `WebClient.Builder` creation in `DefaultWebClientFactory`;
- removed `WebClient.Builder` bean from `ApplicationConfig`.
This solves the bug where the `mTLS` enabled `WebClient` doesn't call external services correctly.
> fix: [SRTP-441] fix WebClient.Builder instantiation

- .github/workflows/post-merge.yml
This PR proposes to fix a check misconfigured in post-deploy tests.
- remove check before installing and running newman.
> fix: [SRTP-442] move step ID to actual release

- src/main/java/it/gov/pagopa/rtp/activator/controller/callback/RequestToPayUpdateController.java
- src/main/java/it/gov/pagopa/rtp/activator/utils/PayloadInfoExtractor.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/callback/RequestToPayUpdateControllerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/utils/PayloadInfoExtractorTest.java
This PR proposes to enrich logs with MDC for service provider.
- update RequestToPayUpdateController to log service_provider
- add PayloadInfoExtractor to manipulate data from different payloads
More detailed logs are needed to enrich the workbook in che callback section, showing callback related to service providers.
> feat: [SRTP-440] enrich callback logs with MDC

- gradle.properties
- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandler.java
- src/main/java/it/gov/pagopa/rtp/activator/exception/ActivationErrorCode.java
- src/main/java/it/gov/pagopa/rtp/activator/exception/SendErrorCode.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/exception/ActivationErrorCodeTest.java
- src/test/java/it/gov/pagopa/rtp/activator/exception/SendErrorCodeTest.java
Add Activation and Send error code enum classes and modify activation 409 error handler.
> chore: [SRTP-429] Manage internal error code.

- .github/workflows/post-merge.yml
- src/test/postman/RTP-component-test.postman_collection.json
- src/test/postman/uat.postman_environment.json
This PR proposes to add new environment variable and secrets to test callback after deploy.
- add new env var
- add new secrets deserialization (cert and key)
With this change we fix a broken test.
> fix: [SRTP-461] Fix post-deploy callback test

- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/RtpStatus.java
This PR will add all `RtpStatus`es needed to describe the possible states that a `RTP` can have in its lifecycle.
- Updated `RtpStatus` with all required statuses.
It enables the full description of a `RTP` lifecycle.
> feat: [SRTP-467] update RTP statuses with all needed states

- src/main/java/it/gov/pagopa/rtp/activator/configuration/mtlswebclient/DefaultWebClientFactory.java
> feat: Pr to deploy last mod that had a refactor name on title instead feat.

- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/Event.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/Rtp.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/RtpEvent.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpEntity.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpMapper.java
- src/test/java/it/gov/pagopa/rtp/activator/repository/rtp/RtpDtoMapperTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SendRTPServiceTest.java
This PR proposes to add `events` to RTP data classes (namely `Rtp` and `RtpEntity`): the field is of type `List<Event>`, where `Event` record contains info about a single event concerning the RTP.
The `Event` class is composed on three fields:
- `timestamp`: the timestamp when the event is recorded;
- `precStatus`: last recorded `RtpStatus`;
- `triggerEvent`: the actual recorded `RtpEvent`.
- Created `Event` record;
- add `events` field in `Rtp` and `RtpEntity` classes;
- updated `RtpMapper` with the new field.
This is needed to keep a ledger of events concerning an RTP, describing its lifetime changes in order to allow better auditability.
> feat: [SRTP-425] add history of events in RTP data classes

- src/main/java/it/gov/pagopa/rtp/activator/domain/rtp/TransactionStatus.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/handler/CancelRtpHandler.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/handler/EpcRequest.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/handler/SendRtpHandler.java
- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/handler/SendRtpProcessorImpl.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/handler/CancelRtpHandlerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/handler/Oauth2HandlerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/handler/RegistryDataHandlerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/handler/SendRtpHandlerTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/handler/SendRtpProcessorImplTest.java
This PR aims to parse the transaction status returned by send `SRTP` API. Due to multiple issues in parsing the full response  body (due to `OpenAPI Generator`not creating an `ApiClient` able to correctly deserialize the response), the `TransactionStatus` is inferred by the `HttpStatus` and the presence or not od the response body.
Also, a slight refactor is don in `SendRtpProcessorImpl` and `EpcRequesst` to accept accept the `TransactionStatus` instead of a full response body.
- Added `TransactionStatus` enum;
- updated `SendRtpHandler` with `TransactionStatus` parsing;
- refactored `SendRtpProcessorImpl` and `EpcRequesst`.
This PR acts as base ground for persisting the `RtpStatus` into the database.
> feat: [SRTP-497] parse transaction status in send RTP flow

- src/main/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapper.java
- src/main/java/it/gov/pagopa/rtp/activator/utils/IdentifierUtils.java
- src/test/java/it/gov/pagopa/rtp/activator/service/rtp/SepaRequestToPayMapperTest.java
- src/test/java/it/gov/pagopa/rtp/activator/utils/IdentifierUtilsTest.java
This PR addresses several validation errors occurring in the request of cancellation fields due to incorrect UUID formatting, invalid values, and incorrect field sizes. Specifically, it introduces the IdentifierUtils class with a method uuidFormatter to standardize UUID formatting and correct issues in the SepaRequestToPayMapper.java where invalid or incorrectly sized fields were causing validation failures.
1. Created the IdentifierUtils class with the uuidFormatter method to handle UUID formatting by removing hyphens.
2. Fixed the validation issues in the cancellation request fields by ensuring:
- Corrected date-time fields to include a timezone offset, ensuring they conform to the expected ISO 8601 format with
timezone
- Used uuidFormatter for all UUID-based fields that failed …
> fix: [SRTP-491] fix cancellation request errors

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImpl.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/payer/DeactivationReason.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/payer/PayerRepository.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/activation/ActivationDBRepository.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/activation/ActivationMapper.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/activation/DeletedActivationDB.java
- src/main/java/it/gov/pagopa/rtp/activator/repository/activation/DeletedActivationEntity.java
- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerService.java
- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImpl.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImplTest.java
- src/test/java/it/gov/pagopa/rtp/activator/repository/activation/ActivationDBRepositoryTest.java
- src/test/java/it/gov/pagopa/rtp/activator/repository/activation/ActivationMapperTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImplTest.java
This PR 's goal is to implement debtor deactivation API. The adopted strategy is to move the entity to be deleted into the new collection `deleted_activations` in order to keep track of previously deleted activations records.
- created `DeactivationReason` enum;
- created entity `DeletedActivationEntity` with corresponding repository `DeletedActivationDB`;
- added new `findById` query in `ActivationDBRepository`;
- added new `deactivate` method in `ActivationDBRepository`;
- added new `findPayerById` and `deactivatePayer` methods in `ActivationPayerService`;
- implement DELETE operation in `ActivationAPIControllerImpl`.
This gives users the ability to deactivate a given debtor activation.
> feat: [SRTP-506] implement debtor deactivation

- .github/workflows/post-merge.yml
> fix: [SRTP-536] Remove quotes.

- CODEOWNERS
> Add codeowners.

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImpl.java
Adds service_provider to MDC in case of activation failure in rtp-activator, so the error log Error activating payer includes the service provider ID.
> fix: [SRTP-600] Add mdc logging on activation failure

- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImpl.java
> fix: [SRTP-647] Remove debtor fiscal code log during activation

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImpl.java
Removed the exception from the logging statement in case of AccessDeniedException, keeping only the exception message.
When logging with the full exception, Application Insights stores only the stack trace and excludes the actual log message. Since the message contains important context needed for monitoring, we removed the exception from the logger to ensure the message is properly captured and indexed.
> fix: [SRTP-653] Update deactivation logs

- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImpl.java
- src/main/java/it/gov/pagopa/rtp/activator/domain/errors/PayerNotFoundException.java
- src/main/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImpl.java
- src/test/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationAPIControllerImplTest.java
- src/test/java/it/gov/pagopa/rtp/activator/service/activation/ActivationPayerServiceImplTest.java
This PR completes the implementation of the `getActivation` method in the `ActivationAPIControllerImpl` class.
The goal is to retrieve an activation using its `activationId`, leveraging the existing `findPayerById` method in the `ActivationPayerServiceImpl` service.
The method has been refined to handle missing records properly and to throw a custom exception `PayerNotFoundException` when needed.
- The getActivation method has been fully implemented in the `ActivationAPIControllerImpl` class. It retrieves the activation based on the `activationId` using the service layer and returns a proper HTTP response based on the result.
- In the `ActivationPayerServiceImpl` class, the `findPayerById` method was refactored to include detailed logging and improved reactive handling. If no payer is …
> feat: [SRTP-610] Implement getActivation endpoint in ActivationAPIControllerImpl

- src/main/terraform/env/itn-dev/terraform.tfvars
> fix: storage account@itn-dev

- .github/workflows/build-n-push-main.yml
> chore: fix the action problem.

- .github/workflows/post-merge.yml
- src/main/java/it/gov/pagopa/rtp/activator/controller/activation/ActivationDtoMapper.java
> fix: [SRTP-808] fix prod deploy.
